# -*- coding: utf-8 -*-
"""LVADSUSR109-Sangavi-IA2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J8tPVj_mQVqR0ZEV5OGXlPucUeWmqkjQ
"""

#1
import numpy as np
rgb_image=np.array([[[255,0,0],[0,255,0],[0,0,255]],
                    [[255,255,0],[255,0,255],[0,255,255]],
                    [[127,127,127],[200,200,200],[50,50,50]]])
print(rgb_image)
print(0.2989*rgb_image[0]+0.5870*rgb_image[1]+0.1140*rgb_image[2])

#2
def fun_nor(nor_arr):


  return nor_arr

data={
    'Height':[145,167,187],
    'Weight':[67,89,56],
    'Age':[34,24,28]
}
nor_arr=np.array(data)
print(nor_arr)
print(fun_nor(nor_arr))

#3
thr_arr=[[[2,3,5],[1,2,4]],[[2,3,5],[1,2,3]],[[3,4,6],[2,3,5]]]
np_ar=np.array(thr_arr)
flat=np_ar.flatten()
print(flat.reshape(1,6))

#4
data=[[['P1','P2','P3'],[30,40,20]],[['P1','P2','P3'],[60,80,50]]]
np_arr=np.array(data)
print(np_arr)
for i in np_arr:

#5
data=[[['S1','S2','S3','S4','S5'],[30,40,20,34,-1]]]
np_arr=np.array(data)
print(np_arr)

#6

def new_fun(data,adj_fac):
    return (data[1]-adj_fac)
data=np.array([[['S1','S2','S3','S4','S5'],[2,3,4,5,6]]])
adj_fac=[0.1,0.3,0.3,0.2,0.1]
print(new_fun(data,adj_fac))

#7
import pandas as pd
data={'Name':['Alice','Bob','Charlie','David','Eve','Frank','Grace'],
      'Age':[25,30,35,40,45,50,55],
      'City':['New York','Los Angeles','Chicago','Houston','Phoenix','Miami','Boston'],
      'Department':['HR','IT','Finance','Marketing','Sales','IT','HR']
      }
df=pd.DataFrame(data)
new_df=df[(df['Age']<45) & (df['Department']!="HR")]
print(new_df)

#8
data={
    'Product':['Apples','Bananas','Cherries','Dates','Elderberries','Flour','Grapes'],
    'Category':['Fruit','Fruit','Fruit','Fruit','Fruit','Bakery','Fruits'],
    'Price':[1.20,0.50,3.00,2.50,4.00,1.50,2.00],
    'Promotion':[True,False,True,True,False,True,False]
}
df=pd.DataFrame(data)
avg_val=df.groupby('Category')['Price'].mean()
print(avg_val)
new_pro=df[(df['Product']=="Fruits")&(df['Promotion']==False)&(df['Price']>avg_val['Fruits'])]
print(new_pro)

#9
employee_data={
    'Employee':['Alice','Bob','Charlie','David'],
    'Department':['HR','IT','Finance','IT'],
    'Manager':['John','Rachel','Emily','Rachel']
}
project_data={
    'Employee':['Alice','Charlie','Eve'],
    'Project':['P1','P3','P2']
}
df1=pd.DataFrame(employee_data)
df2=pd.DataFrame(project_data)

merged_df=pd.merge(df1,df2)
print(merged_df)

#10
data={
    'Department':['Electronics','Electronics','Clothing','Clothing','HomeGoods'],
    'Salesperson':['Alice','Bob','Charlie','David','Eve'],
    'Sales':[70000,50000,30000,40000,60000]
}
df=pd.DataFrame(data)
new_df=df.groupby('Department')['Sales'].mean()
print((new_df))